#!/usr/bin/perl

# Copyright 2012, Yohei Yamaguchi <joker13meister@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following disclaimer
# in the documentation and/or other materials provided with the
# distribution.
#     * Neither the name of Google Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# run a chromium-browser with an appropriate proxy setting
# according to your current IP address.

# TODO: move settings of IPs and proxys to a yaml file

use strict;
use warnings;
use feature ":5.10";

my @interface_tmpls = qw/eth ppp wlan/;

my ($chromium) = grep { -e $_ } qw(
        /usr/bin/chromium-browser
        /usr/local/bin/chromium-browser
);
die "chromium-browser is not found" unless $chromium;

# parse the result of ifconfig
# try from 0 to 10 for each interface
for my $tmpl (@interface_tmpls) {
    for my $i (0 .. 10) {
        my $interface = $tmpl.$i;
        open(IFCONFIG, "LANG=C ifconfig $interface 2>&1 |") or die $!;
        for (<IFCONFIG>) {
            chomp;
            if (m/inet addr:([^\s]+)/ && $1 ne "127.0.0.1") {
                my $IP = $1;
                run_chromium($IP);
                exit(0);
             }
        }
        close(IFCONFIG);
    }
}
die "Error: trial failed.\nIs Internet connection is available?\n";

# run chromium-browser according to the current IP address
sub run_chromium{
    my ($IP) = @_;
    given ($IP) {
        when (/^10\.2\d{0,2}.\d{1,3}\.\d{1,3}$/) { `$chromium --proxy-server="proxy.kuins.net:8080"` }
        when (/^172\.16\.33\.\d{1,3}$/)          { `$chromium --proxy-server="proxy.kuins.net:8080"` }
        when (/^192\.168\.11\.\d{1,3}$/)         { `$chromium` }
        default                                  { die "Error: no IP address matches\n" }
    }
}
